# Generated by Django 6.0.2 on 2026-07-13 22:48

import apps.accounts.models.pending_registration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('password_hash', models.CharField(max_length=255)),
                ('position_title', models.CharField(blank=True, max_length=20)),
                ('school_name', models.CharField(max_length=255)),
                ('school_email', models.EmailField(blank=True, max_length=254)),
                ('school_phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Ghana', max_length=100)),
                ('school_type', models.CharField(blank=True, max_length=20)),
                ('expected_student_count', models.CharField(blank=True, max_length=20)),
                ('otp', models.CharField(default=apps.accounts.models.pending_registration.generate_otp, max_length=6)),
                ('otp_created_at', models.DateTimeField(auto_now_add=True)),
                ('otp_expires_at', models.DateTimeField(default=apps.accounts.models.pending_registration.otp_expiry)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=apps.accounts.models.pending_registration.pending_expiry)),
            ],
            options={
                'verbose_name': 'Pending Registration',
                'verbose_name_plural': 'Pending Registrations',
            },
        ),
    ]
