# Generated by Django 6.0.2 on 2026-07-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pendingregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneVerificationOTP',
        ),
    ]
