# Generated by Django 6.0.2 on 2026-08-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_phoneverificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffportalinvite',
            name='role',
            field=models.CharField(default='teacher', help_text='Role granted when the invite is accepted.', max_length=20),
        ),
    ]
