# Generated by Django 6.0.2 on 2026-08-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_staffportalinvite_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, help_text='The name this person signs in with, chosen by them at setup. Stored lowercase. Null for accounts created before usernames.', max_length=30, null=True, unique=True),
        ),
    ]
