# Generated by Django 6.0.2 on 2026-07-21 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_cacomponenttype_cacomponent_cacomponentscore_cascore'),
    ]

    operations = [
        migrations.CreateModel(
            name='GESCalendarTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. '2026/2027'", max_length=20, unique=True)),
                ('start_date', models.DateField(help_text='First day of Term 1')),
                ('end_date', models.DateField(help_text='Official end of the academic year')),
                ('exam_start_date', models.DateField(blank=True, help_text='BECE start date, if published', null=True)),
                ('exam_end_date', models.DateField(blank=True, help_text='BECE end date, if published', null=True)),
                ('source_note', models.CharField(blank=True, help_text='Where this was sourced from, for verification later', max_length=255)),
                ('published_on', models.DateField(blank=True, help_text='Date GES issued the release', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from the setup dropdown without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GES Calendar Template',
                'verbose_name_plural': 'GES Calendar Templates',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='GESCalendarTermTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('term_1', 'Term 1'), ('term_2', 'Term 2'), ('term_3', 'Term 3')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('vacation_start_date', models.DateField(blank=True, null=True)),
                ('vacation_end_date', models.DateField(blank=True, null=True)),
                ('midterm_start_date', models.DateField(blank=True, null=True)),
                ('midterm_end_date', models.DateField(blank=True, null=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.gescalendartemplate')),
            ],
            options={
                'verbose_name': 'GES Calendar Term Template',
                'verbose_name_plural': 'GES Calendar Term Templates',
                'ordering': ['name'],
                'unique_together': {('calendar', 'name')},
            },
        ),
    ]
