# Generated by Django 6.0.2 on 2026-08-25 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_classworkrecord_submitted_by_classworksubmission_and_more'),
        ('tenants', '0007_schoolmember_is_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_ending', models.DateField(help_text='Friday of the week this plan covers.')),
                ('class_size', models.PositiveIntegerField(blank=True, null=True)),
                ('strand', models.CharField(blank=True, max_length=200)),
                ('sub_strand', models.CharField(blank=True, max_length=200)),
                ('indicator_code', models.CharField(blank=True, help_text='e.g. B4-4-4-1-1', max_length=50)),
                ('content_standard_code', models.CharField(blank=True, help_text='e.g. B4-4-4-1', max_length=50)),
                ('performance_indicator', models.TextField(blank=True)),
                ('core_competencies', models.TextField(blank=True)),
                ('key_words', models.TextField(blank=True)),
                ('tlr', models.TextField(blank=True, help_text='Teaching and learning resources.')),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('vetted', 'Vetted'), ('returned', 'Returned for revision')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('vetted_at', models.DateTimeField(blank=True, null=True)),
                ('vetting_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.branch')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='academics.classroom')),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='tenants.schoolmember')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='tenants.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='academics.term')),
                ('vetted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vetted_lesson_plans', to='tenants.schoolmember')),
            ],
            options={
                'ordering': ['-week_ending'],
                'unique_together': {('classroom', 'subject', 'term', 'week_ending')},
            },
        ),
        migrations.CreateModel(
            name='LessonPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('period', models.CharField(blank=True, help_text='e.g. 1 hour, Period 3.', max_length=50)),
                ('phase_1_starter', models.TextField(blank=True, help_text='Preparing the brain for learning.')),
                ('phase_2_main', models.TextField(blank=True, help_text='New learning including assessment.')),
                ('phase_3_plenary', models.TextField(blank=True, help_text='Plenary and reflections.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='academics.lessonplan')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('plan', 'day')},
            },
        ),
    ]
