# Generated by Django 6.0.2 on 2026-07-20 10:03

import apps.communications.models.consent_request
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_cacomponenttype_cacomponent_cacomponentscore_cascore'),
        ('students', '0007_alter_enrolmentinvite_submitted_data'),
        ('tenants', '0005_schoolmember_has_seen_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classrooms', models.ManyToManyField(blank=True, related_name='excursions', to='academics.classroom')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_excursions', to='tenants.schoolmember')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursions', to='tenants.school')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('first_aid', 'First Aid Administration'), ('image_use', "Use of Child's Image / Likeness"), ('excursion', 'Excursion / Trip'), ('other', 'Other')], max_length=15)),
                ('method', models.CharField(choices=[('digital_link', 'Digital Link'), ('manual', 'Manual (Physical Signature on File)')], max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('granted', 'Granted'), ('denied', 'Denied'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('signed_name', models.CharField(blank=True, max_length=200)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to=apps.communications.models.consent_request.consent_signature_path)),
                ('response_notes', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_requests', to='students.guardian')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_consent_requests', to='tenants.schoolmember')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_requests', to='students.student')),
                ('excursion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_requests', to='communications.excursion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
