# Generated by Django 6.0.2 on 2026-07-20 10:59

import apps.communications.models.consent_request
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentrequest',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.communications.models.consent_request.consent_pdf_path),
        ),
    ]
