# Generated by Django 6.0.2 on 2026-07-26 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_fix_class_level_order'),
        ('communications', '0002_consentrequest_pdf_file'),
        ('students', '0007_alter_enrolmentinvite_submitted_data'),
        ('tenants', '0007_schoolmember_is_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal label for this message — not sent to recipients.', max_length=150)),
                ('body', models.TextField(help_text='The actual SMS text. Links (e.g. an enrolment invite URL) can be included directly in this text.')),
                ('audience_type', models.CharField(choices=[('single_guardian', 'Single Guardian'), ('single_staff', 'Single Staff Member'), ('class_guardians', "A Class's Guardians"), ('all_staff', 'All Staff'), ('all_guardians', 'All Guardians (Broadcast)')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('sent', 'Sent'), ('declined', 'Declined'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=255)),
                ('recipient_count', models.PositiveIntegerField(default=0, help_text='How many distinct phone numbers this actually reached, filled in at send time after audience resolution + dedup.')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('composed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_composed', to='tenants.schoolmember')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Who approved or declined — null if composed_by is already admin-tier and it went straight through.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_reviewed', to='tenants.schoolmember')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tenants.school')),
                ('target_classroom', models.ForeignKey(blank=True, help_text="Set when audience_type='class_guardians'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_targeted', to='academics.classroom')),
                ('target_staff_member', models.ForeignKey(blank=True, help_text="Set when audience_type='single_staff'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_received_as_target', to='tenants.schoolmember')),
                ('target_student', models.ForeignKey(blank=True, help_text="Set when audience_type='single_guardian' — message goes to this student's primary guardian.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_targeted', to='students.student')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
