# Generated by Django 6.0.2 on 2026-03-01 21:39

import apps.students.models.student
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('tenants', '0002_school_onboarding_complete_school_onboarding_step'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('brother', 'Brother'), ('sister', 'Sister'), ('guardian', 'Legal Guardian'), ('other', 'Other')], max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('nationality', models.CharField(blank=True, default='Ghanaian', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('residential_address', models.TextField(blank=True)),
                ('is_fee_payer', models.BooleanField(default=False, help_text='Is this guardian responsible for paying school fees?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('place_of_birth', models.CharField(blank=True, max_length=200)),
                ('home_town', models.CharField(blank=True, max_length=200)),
                ('nationality', models.CharField(default='Ghanaian', max_length=100)),
                ('mother_tongue', models.CharField(blank=True, max_length=100)),
                ('birth_certificate_number', models.CharField(blank=True, max_length=100)),
                ('nhis_number', models.CharField(blank=True, max_length=50, verbose_name='NHIS Card Number')),
                ('residential_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, choices=[('greater_accra', 'Greater Accra'), ('ashanti', 'Ashanti'), ('western', 'Western'), ('western_north', 'Western North'), ('central', 'Central'), ('eastern', 'Eastern'), ('volta', 'Volta'), ('oti', 'Oti'), ('northern', 'Northern'), ('savannah', 'Savannah'), ('north_east', 'North East'), ('upper_east', 'Upper East'), ('upper_west', 'Upper West'), ('bono', 'Bono'), ('bono_east', 'Bono East'), ('ahafo', 'Ahafo'), ('other', 'Other / Outside Ghana')], max_length=30)),
                ('religion', models.CharField(blank=True, choices=[('christian', 'Christian'), ('muslim', 'Muslim'), ('traditionalist', 'Traditionalist'), ('other', 'Other'), ('none', 'None / Prefer not to say')], max_length=20)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('known_allergies', models.TextField(blank=True)),
                ('medical_notes', models.TextField(blank=True)),
                ('disability_status', models.BooleanField(default=False)),
                ('disability_description', models.TextField(blank=True)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_school', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn'), ('suspended', 'Suspended'), ('deceased', 'Deceased')], default='active', max_length=15)),
                ('withdrawal_reason', models.TextField(blank=True)),
                ('boarding_status', models.CharField(choices=[('day', 'Day Student'), ('boarder', 'Full Boarder'), ('weekly', 'Weekly Boarder')], default='day', max_length=10)),
                ('house_dormitory', models.CharField(blank=True, max_length=100)),
                ('bus_route', models.CharField(blank=True, max_length=100)),
                ('locker_number', models.CharField(blank=True, max_length=20)),
                ('talents_skills', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.students.models.student.student_photo_path)),
                ('fingerprint_data', models.FileField(blank=True, null=True, upload_to=apps.students.models.student.student_fingerprint_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='tenants.branch')),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.classroom')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='tenants.school')),
                ('siblings', models.ManyToManyField(blank=True, related_name='sibling_of', to='students.student')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('brother', 'Brother'), ('sister', 'Sister'), ('guardian', 'Legal Guardian'), ('family_friend', 'Family Friend'), ('other', 'Other')], max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Call this person first in an emergency')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='students.student')),
            ],
            options={
                'ordering': ['-is_primary', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentClassHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=True)),
                ('promoted', models.BooleanField(blank=True, help_text='Was the student promoted at end of year? Null = not yet determined', null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_history', to='academics.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_history', to='academics.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_history', to='students.student')),
            ],
            options={
                'ordering': ['-academic_year__start_date'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary contact for this student')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_guardians', to='students.guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_guardians', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'guardian')},
            },
        ),
    ]
