# Generated by Django 6.0.2 on 2026-07-16 10:48

import apps.students.models.guardian
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0002_alter_student_enrollment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardian',
            old_name='occupation',
            new_name='occupation_old',
        ),
        migrations.AddField(
            model_name='guardian',
            name='can_pickup',
            field=models.BooleanField(default=True, help_text='Authorized to pick up the student'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='digital_address',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='guardian',
            name='fingerprint_data',
            field=models.FileField(blank=True, null=True, upload_to=apps.students.models.guardian.guardian_fingerprint_path),
        ),
        migrations.AddField(
            model_name='guardian',
            name='ghana_card_back',
            field=models.ImageField(blank=True, null=True, upload_to=apps.students.models.guardian.guardian_document_path),
        ),
        migrations.AddField(
            model_name='guardian',
            name='ghana_card_front',
            field=models.ImageField(blank=True, null=True, upload_to=apps.students.models.guardian.guardian_document_path),
        ),
        migrations.AddField(
            model_name='guardian',
            name='ghana_card_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='guardian',
            name='occupation_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardians', to='core.occupation'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.students.models.guardian.guardian_photo_path),
        ),
        migrations.AddField(
            model_name='guardian',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='guardian',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('miss', 'Miss'), ('dr', 'Dr.'), ('prof', 'Prof.'), ('rev', 'Rev.'), ('pastor', 'Pastor'), ('alhaji', 'Alhaji'), ('hajia', 'Hajia'), ('hon', 'Hon.'), ('other', 'Other')], max_length=10),
        ),
    ]
