# Generated by Django 6.0.2 on 2026-07-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_occupation_guardian_occupation_old_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardian',
            old_name='occupation_new',
            new_name='occupation',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='occupation_old',
        ),
    ]
