# Generated by Django 6.0.2 on 2026-07-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_occupation_new_guardian_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ghana_card_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Ghana Card Number'),
        ),
    ]
