# Generated by Django 6.0.2 on 2026-07-19 17:44

import apps.students.models.enrolment_invite
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_ghana_card_number'),
        ('tenants', '0005_schoolmember_has_seen_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolmentInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('prospective_first_name', models.CharField(max_length=100)),
                ('prospective_last_name', models.CharField(max_length=100)),
                ('parent_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('submitted_data', models.JSONField(blank=True, null=True)),
                ('submitted_photo', models.ImageField(blank=True, null=True, upload_to=apps.students.models.enrolment_invite.invite_photo_path)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolment_invite', to='students.student')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_enrolment_invites', to='tenants.schoolmember')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_enrolment_invites', to='tenants.schoolmember')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolment_invites', to='tenants.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
