# Generated by Django 6.0.2 on 2026-07-20 10:03

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_enrolmentinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolmentinvite',
            name='submitted_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
