# Generated by Django 6.0.2 on 2026-07-14 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_alter_student_enrollment_date'),
        ('tenants', '0005_schoolmember_has_seen_tour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('recommendation_letter', 'Recommendation Letter'), ('introduction_letter', 'Introduction Letter'), ('transcript', 'Transcript'), ('transfer_letter', 'Transfer Letter'), ('financial_clearance', 'Financial Clearance'), ('custom', 'Custom')], max_length=30)),
                ('body_html', models.TextField(help_text='HTML with {{placeholder}} tokens. For computed docs, this is the wrapper/letterhead containing {{computed_content}}.')),
                ('extra_fields', models.JSONField(blank=True, default=list, help_text="Admin-fillable fields at generation time, e.g. [{'token': 'embassy_name', 'label': 'Embassy Name', 'type': 'text', 'required': True}]")),
                ('requires_signature', models.BooleanField(default=True)),
                ('is_computed', models.BooleanField(default=False, help_text='True for Transcript-style docs assembled from real data, not free text.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='tenants.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('merged_content', models.TextField(help_text='Final rendered HTML at time of generation — frozen, not re-rendered live.')),
                ('pdf_file', models.FileField(upload_to='generated_documents/%Y/%m/')),
                ('context_snapshot', models.JSONField(blank=True, default=dict, help_text='Raw data used to fill placeholders, kept for audit/debug.')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_generated', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='students.student')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to='documents.documenttemplate')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
