# Generated by Django 6.0.2 on 2026-07-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_school_onboarding_complete_school_onboarding_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='expected_student_count',
            field=models.CharField(blank=True, choices=[('under_100', 'Under 100'), ('100_300', '100 – 300'), ('300_600', '300 – 600'), ('600_plus', '600+')], max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(blank=True, choices=[('basic', 'Basic / JHS'), ('shs', 'Senior High School'), ('international', 'International School'), ('group', 'Multi-branch Group')], max_length=20),
        ),
    ]
