# Generated by Django 6.0.2 on 2026-07-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_school_expected_student_count_school_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmember',
            name='position_title',
            field=models.CharField(blank=True, choices=[('proprietor', 'Proprietor / Owner'), ('head_teacher', 'Head Teacher / Principal'), ('administrator', 'Administrator'), ('other', 'Other')], help_text="Descriptive title for this person's position at the school — informational only, does not affect permissions.", max_length=20),
        ),
    ]
