# Generated by Django 6.0.2 on 2026-07-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_schoolmember_position_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmember',
            name='has_seen_tour',
            field=models.BooleanField(default=False),
        ),
    ]
