# Generated by Django 6.0.2 on 2026-07-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_schoolmember_has_seen_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmember',
            name='role',
            field=models.CharField(choices=[('school_admin', 'School Administrator'), ('branch_manager', 'Branch Manager'), ('teacher', 'Teacher'), ('accountant', 'Accountant'), ('registrar', 'Registrar'), ('receptionist', 'Receptionist')], max_length=20),
        ),
    ]
