# Generated by Django 6.0.2 on 2026-07-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_alter_schoolmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmember',
            name='is_lead',
            field=models.BooleanField(default=False, help_text="Senior/primary person within this role at this school (e.g. the Main Accountant vs additional accountants). Unlocks sensitive within-domain actions — does NOT affect whether the domain itself is accessible; that's role-based, see apps/tenants/permissions.py."),
        ),
    ]
