# Generated by Django 6.0.2 on 2026-08-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_schoolmember_is_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmember',
            name='role',
            field=models.CharField(choices=[('school_admin', 'School Administrator'), ('branch_manager', 'Branch Manager'), ('teacher', 'Teacher'), ('head_of_academics', 'Head of Academics'), ('accountant', 'Accountant'), ('registrar', 'Registrar'), ('receptionist', 'Receptionist')], max_length=20),
        ),
    ]
