# Generated by Django 6.0.2 on 2026-08-29 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_alter_schoolmember_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What this school calls the job, e.g. Assistant Head Teacher.', max_length=60)),
                ('slug', models.SlugField(help_text='Stable identifier. Does not change when the name does.', max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_default', models.BooleanField(default=False, help_text='Seeded with the school. Can be renamed, cannot be deleted.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenants.school')),
            ],
            options={
                'ordering': ['school', 'name'],
                'unique_together': {('school', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=30)),
                ('level', models.CharField(choices=[('view', 'View only'), ('request', 'Can request, needs approval'), ('full', 'Full access')], max_length=10)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='tenants.schoolrole')),
            ],
            options={
                'ordering': ['role', 'domain'],
                'unique_together': {('role', 'domain')},
            },
        ),
    ]
