# Generated by Django 6.0.2 on 2026-08-29 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_schoolrole_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmember',
            name='role_ref',
            field=models.ForeignKey(blank=True, help_text='The role this person holds. Replaces the legacy role string, which is kept until every reader has moved across.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='tenants.schoolrole'),
        ),
    ]
