# Generated by Django 5.0 on 2026-09-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_update_role_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='curriculum',
            field=models.CharField(choices=[('ges', 'GES (Ghana Education Service)'), ('cambridge', 'Cambridge'), ('hybrid', 'Hybrid (GES and Cambridge)')], default='ges', help_text='Which curriculum this school follows.', max_length=20),
        ),
    ]
