# Generated by Django 5.0 on 2026-09-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_school_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='curriculum',
            field=models.CharField(blank=True, choices=[('ges', 'GES (Ghana Education Service)'), ('cambridge', 'Cambridge'), ('hybrid', 'Hybrid (GES and Cambridge)')], help_text='Which curriculum this school follows. Chosen during setup rather than at registration, so registration stays short.', max_length=20),
        ),
    ]
