# Generated by Django 6.0.2 on 2026-08-22 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0004_fix_class_level_order'),
        ('students', '0007_alter_enrolmentinvite_submitted_data'),
        ('tenants', '0007_schoolmember_is_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(help_text='The full assignment text — what a parent sees in full when she opens it.')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='classroom/assignments/')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('allows_digital_submission', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to='tenants.schoolmember')),
                ('subject_assignment', models.ForeignKey(help_text='Ties this to the exact teacher × subject × classroom × term combination it belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='classroom_assignments', to='academics.subjectassignment')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_done', 'Not Done'), ('done', 'Done'), ('submitted', 'Submitted'), ('graded', 'Graded')], default='not_done', max_length=15)),
                ('submitted_file', models.FileField(blank=True, null=True, upload_to='classroom/submissions/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='classroom.assignment')),
                ('marked_by', models.ForeignKey(blank=True, help_text='Which teacher marked this — relevant for the checklist track where a teacher sets status directly.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_completions_marked', to='tenants.schoolmember')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_completions', to='students.student')),
            ],
            options={
                'verbose_name': 'Assignment Completion',
                'verbose_name_plural': 'Assignment Completions',
                'ordering': ['student__last_name', 'student__first_name'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
