# Generated by Django 6.0.2 on 2026-03-02 17:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0002_alter_student_enrollment_date'),
        ('teachers', '0001_initial'),
        ('tenants', '0002_school_onboarding_complete_school_onboarding_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='absent', max_length=10)),
                ('clock_in_time', models.TimeField(blank=True, null=True)),
                ('clock_out_time', models.TimeField(blank=True, help_text='Time staff member clocked out.', null=True)),
                ('remarks', models.TextField(blank=True)),
                ('via_fingerprint', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_attendances', to='tenants.branch')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendances', to='tenants.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='teachers.staffprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendances', to='academics.term')),
            ],
            options={
                'verbose_name': 'Staff Attendance',
                'verbose_name_plural': 'Staff Attendance Records',
                'ordering': ['-date', 'staff__last_name'],
                'unique_together': {('staff', 'date', 'term')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='absent', max_length=10)),
                ('clock_in_time', models.TimeField(blank=True, help_text='Time student clocked in — recorded by fingerprint device or manually.', null=True)),
                ('remarks', models.TextField(blank=True)),
                ('via_fingerprint', models.BooleanField(default=False, help_text='Was this attendance recorded via fingerprint device?')),
                ('guardian_notified', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_attendances', to='tenants.branch')),
                ('marked_by', models.ForeignKey(blank=True, help_text='Staff member who marked this attendance record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to='tenants.schoolmember')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendances', to='academics.term')),
            ],
            options={
                'verbose_name': 'Student Attendance',
                'verbose_name_plural': 'Student Attendance Records',
                'ordering': ['-date', 'student__last_name'],
                'unique_together': {('student', 'date', 'term')},
            },
        ),
    ]
