# Generated by Django 6.0.2 on 2026-03-03 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('students', '0002_alter_student_enrollment_date'),
        ('tenants', '0002_school_onboarding_complete_school_onboarding_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffattendance',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Computed automatically from clock in/out times.', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='source',
            field=models.CharField(choices=[('fingerprint', 'Fingerprint Device'), ('manual', 'Manual Entry')], default='manual', max_length=15),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='clock_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='clock_out_via_fingerprint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='early_dismissal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='early_dismissal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='locked',
            field=models.BooleanField(default=False, help_text='Fingerprint records are locked. Editing requires admin + override reason.'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_overrides', to='tenants.schoolmember'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='pickup_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups_verified', to='tenants.schoolmember'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='source',
            field=models.CharField(choices=[('fingerprint', 'Fingerprint Device'), ('manual', 'Manual Entry'), ('system', 'System Generated')], default='manual', help_text='How this record was created.', max_length=15),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='clock_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='clock_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='via_fingerprint',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AuthorisedPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('grandfather', 'Grandfather'), ('grandmother', 'Grandmother'), ('brother', 'Brother'), ('sister', 'Sister'), ('guardian', 'Legal Guardian'), ('driver', 'Driver'), ('family_friend', 'Family Friend'), ('other', 'Other')], max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('ghana_card_number', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, help_text='Photo for visual verification by gate staff.', null=True, upload_to='authorised_pickups/')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorised_pickups_added', to='tenants.schoolmember')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorised_pickups', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorised_pickups', to='students.student')),
            ],
            options={
                'verbose_name': 'Authorised Pickup Person',
                'verbose_name_plural': 'Authorised Pickup Persons',
                'ordering': ['student__last_name', 'last_name'],
            },
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='picked_up_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups', to='attendance.authorisedpickup'),
        ),
        migrations.CreateModel(
            name='PickupIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_by_name', models.CharField(max_length=200)),
                ('attempted_by_phone', models.CharField(blank=True, max_length=20)),
                ('attempted_by_id_number', models.CharField(blank=True, max_length=50)),
                ('reason_given', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('authorisation_sms_sent', models.BooleanField(default=False)),
                ('authorisation_sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('guardian_response_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending - Awaiting Guardian Response'), ('authorised', 'Authorised - Student Released'), ('denied', 'Denied - Student Retained'), ('escalated', 'Escalated - Head Teacher Notified')], default='pending', max_length=20)),
                ('student_released', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('escalated', models.BooleanField(default=False)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardian_notified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_incidents_notified', to='students.guardian')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_incidents_resolved', to='tenants.schoolmember')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_incidents', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_incidents', to='students.student')),
            ],
            options={
                'verbose_name': 'Pickup Incident',
                'verbose_name_plural': 'Pickup Incidents',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_start_time', models.TimeField(default='07:30')),
                ('late_grace_minutes', models.PositiveIntegerField(default=15)),
                ('school_close_time', models.TimeField(default='15:00')),
                ('unclocked_out_alert_time', models.TimeField(default='15:30', help_text='Time to alert teacher and guardian for students not yet clocked out.')),
                ('allow_fingerprint_exit', models.BooleanField(default=False)),
                ('sms_on_checkin', models.BooleanField(default=True)),
                ('sms_on_checkout', models.BooleanField(default=True)),
                ('sms_on_late_arrival', models.BooleanField(default=True)),
                ('sms_on_absence', models.BooleanField(default=True)),
                ('absence_notify_time', models.TimeField(default='09:00', help_text='Time to send absence SMS for students who have not checked in.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Leave blank for school-wide settings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_settings', to='tenants.branch')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_settings', to='tenants.school')),
            ],
            options={
                'verbose_name': 'Attendance Settings',
                'verbose_name_plural': 'Attendance Settings',
                'unique_together': {('school', 'branch')},
            },
        ),
    ]
