# Generated by Django 6.0.2 on 2026-03-02 15:21

import apps.teachers.models.staff_profile
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('tenants', '0002_school_onboarding_complete_school_onboarding_step'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('nationality', models.CharField(default='Ghanaian', max_length=100)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10)),
                ('number_of_dependants', models.PositiveIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.teachers.models.staff_profile.staff_photo_path)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('residential_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, choices=[('greater_accra', 'Greater Accra'), ('ashanti', 'Ashanti'), ('western', 'Western'), ('western_north', 'Western North'), ('central', 'Central'), ('eastern', 'Eastern'), ('volta', 'Volta'), ('oti', 'Oti'), ('northern', 'Northern'), ('savannah', 'Savannah'), ('north_east', 'North East'), ('upper_east', 'Upper East'), ('upper_west', 'Upper West'), ('bono', 'Bono'), ('bono_east', 'Bono East'), ('ahafo', 'Ahafo'), ('other', 'Other / Outside Ghana')], max_length=30)),
                ('ghana_card_number', models.CharField(blank=True, max_length=50)),
                ('ssnit_number', models.CharField(blank=True, max_length=50, verbose_name='SSNIT Number')),
                ('ntc_license_number', models.CharField(blank=True, max_length=50, verbose_name='NTC License Number')),
                ('highest_qualification', models.CharField(blank=True, choices=[('wassce', 'WASSCE'), ('diploma', 'Diploma'), ('bachelors', "Bachelor's Degree"), ('pgde', 'PGDE'), ('masters', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], max_length=20)),
                ('institution_attended', models.CharField(blank=True, max_length=255)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('part_time', 'Part Time'), ('national_service', 'National Service'), ('volunteer', 'Volunteer')], default='permanent', max_length=20)),
                ('salary_grade', models.CharField(blank=True, max_length=50)),
                ('date_of_first_appointment', models.DateField(blank=True, null=True)),
                ('date_joined_school', models.DateField(blank=True, null=True)),
                ('is_on_probation', models.BooleanField(default=False)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('resigned', 'Resigned'), ('retired', 'Retired'), ('deceased', 'Deceased')], default='active', max_length=15)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True)),
                ('is_head_of_department', models.BooleanField(default=False)),
                ('leave_entitlement_days', models.PositiveIntegerField(default=21)),
                ('leave_days_taken', models.PositiveIntegerField(default=0)),
                ('bank_name', models.CharField(blank=True, choices=[('gcb', 'GCB Bank'), ('ecobank', 'Ecobank'), ('absa', 'Absa Bank'), ('stanbic', 'Stanbic Bank'), ('zenith', 'Zenith Bank'), ('uba', 'UBA Ghana'), ('fidelity', 'Fidelity Bank'), ('calbank', 'CalBank'), ('agricultural', 'Agricultural Development Bank'), ('prudential', 'Prudential Bank'), ('republic', 'Republic Bank'), ('societe', 'Societe Generale'), ('access', 'Access Bank'), ('other', 'Other')], max_length=20)),
                ('bank_branch', models.CharField(blank=True, max_length=200)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('momo_number', models.CharField(blank=True, max_length=20, verbose_name='MoMo Number')),
                ('next_of_kin_name', models.CharField(blank=True, max_length=200)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=100)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20)),
                ('next_of_kin_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='tenants.branch')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='tenants.school')),
                ('subject_specializations', models.ManyToManyField(blank=True, related_name='specialist_staff', to='academics.subject')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
