# Generated by Django 6.0.2 on 2026-07-17 20:48

import apps.teachers.models.staff_profile
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_position'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='digital_address',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='fingerprint_data',
            field=models.FileField(blank=True, null=True, upload_to=apps.teachers.models.staff_profile.staff_fingerprint_path),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='ghana_card_back',
            field=models.ImageField(blank=True, null=True, upload_to=apps.teachers.models.staff_profile.staff_document_path),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='ghana_card_front',
            field=models.ImageField(blank=True, null=True, upload_to=apps.teachers.models.staff_profile.staff_document_path),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='core.position'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='staff_category',
            field=models.CharField(blank=True, choices=[('teaching', 'Teaching'), ('non_teaching', 'Non-Teaching'), ('support', 'Support'), ('management', 'Management')], max_length=15),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='time_commitment',
            field=models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time')], default='full_time', max_length=10),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='title',
            field=models.CharField(blank=True, choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('miss', 'Miss'), ('madam', 'Madam'), ('dr', 'Dr.'), ('prof', 'Prof.'), ('rev', 'Rev.'), ('pastor', 'Pastor'), ('alhaji', 'Alhaji'), ('hajia', 'Hajia'), ('hon', 'Hon.'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='highest_qualification',
            field=models.CharField(blank=True, choices=[('wassce', 'WASSCE'), ('hnd', 'HND'), ('diploma', 'Diploma'), ('bachelors', "Bachelor's Degree"), ('pgde', 'PGDE'), ('masters', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='StaffEmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('child', 'Child'), ('relative', 'Other Relative'), ('friend', 'Friend'), ('other', 'Other')], max_length=15)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='teachers.staffprofile')),
            ],
            options={
                'ordering': ['-is_primary', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('award', 'Award'), ('commendation', 'Commendation'), ('warning', 'Warning'), ('disciplinary', 'Disciplinary Note')], max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_records_recorded', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='teachers.staffprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
