# Generated by Django 6.0.2 on 2026-08-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_staffprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='teaches',
            field=models.BooleanField(default=False, help_text='Whether this person can be assigned classes and subjects. Separate from staff_category so a bursar or head of academics who also teaches can still appear on the assignment screen.', verbose_name='Teaches classes'),
        ),
    ]
