# Generated by Django 6.0.2 on 2026-08-31 13:21

import apps.agamotto.models.support
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agamotto', '0001_initial'),
        ('tenants', '0012_update_role_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Why this session was opened. Shown to the school in the summary.')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=apps.agamotto.models.support.session_expiry)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('summary_sent_at', models.DateTimeField(blank=True, null=True)),
                ('summary_sent_to', models.EmailField(blank=True, max_length=254)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_sessions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_sessions', to='tenants.school')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('query', models.CharField(blank=True, max_length=255)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='agamotto.supportsession')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportsession',
            index=models.Index(fields=['school', 'closed_at'], name='agamotto_su_school__22443a_idx'),
        ),
        migrations.AddIndex(
            model_name='supportaccesslog',
            index=models.Index(fields=['session', 'at'], name='agamotto_su_session_405b2e_idx'),
        ),
    ]
