# Generated by Django 6.0.2 on 2026-07-24 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        ('notifications', '0001_initial'),
        ('students', '0007_alter_enrolmentinvite_submitted_data'),
        ('tenants', '0007_schoolmember_is_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReminderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, help_text="Optional context from the requester — e.g. 'third reminder, please call rather than SMS'.")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved — sent'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=255)),
                ('message_sent', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders_requested', to='tenants.schoolmember')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reminders_reviewed', to='tenants.schoolmember')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminder_requests', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminder_requests', to='students.student')),
                ('student_fee', models.ForeignKey(blank=True, help_text='The specific fee this reminder concerns, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_requests', to='fees.studentfee')),
            ],
            options={
                'verbose_name': 'Payment Reminder Request',
                'verbose_name_plural': 'Payment Reminder Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
